### ISSUE TITLE
monitor.addr.list can not be modified.

### ISSUE THREAD

**Issue by yc593204787** [JeffersonLab/epics2kafka#5]
monitor.addr.list can not be modified. I changed softioc into the real IP address of IOC, but the connection cannot be established successfully. Is its value a fixed string, or an array of strings? Base7.0.5 and Base3.15.8 were used in the test respectively.

**Comment by slominskir** [comment]
The docker containers are running in their own isolated network and by default do not allow access with outside hosts.   Either install epics2kafka on a host in the same network as your IOC or update the docker-compose.yml to allow access.

**Comment by yc593204787** [comment]
Thank you very much. According to your suggestion, I have created a new network in docker-comemage. yml and solved this problem.
